### PR TITLE
let users combine their balance

### LINKED ISSUE #2: feat: Let costumers combine balances from any token to pay
The user should be able to multiselect multiple token balances in order to pay.

Also will be good to create a separate component for the modal.

https://github.com/StrapexLabs/strapex/blob/main/frontend/src/app/(payments)/p/%5Bid%5D/page.tsx

For example:
10$ worth ETH + 15$ USDC = 25 $USDC

**This will even enable paying with memecoins**

In order to achieve this we will have to fetch quotes for every token balance portion and submit along the payment transaction.

image

### PR DESCRIPTION
**Pull request by wheval**
fixes #2

### CODE REVIEW

**Comment by machuwey** [comment]
Hi @wheval , 
1. We intend to have a one slide control, which will divide the total balance between each specified token (if there is two choosen).
Right now I see that there is two triggers on the slider and the behaviour is quite confusing. Please refer a to the specified design. 
3. If there is only one token choosen, we don't need to show the slider at all (aka. make it reactive)

image

**Comment by wheval** [comment]
Hello @machuwey . So what i understand is ; The total price should be divided among the selected tokens.
Also, should there be a max no of tokens a user can combine?

**Comment by machuwey** [comment]
> Hello @machuwey . So what i understand is ; The total price should be divided among the selected tokens. Also, should there be a max no of tokens a user can combine?

Yes, that's right. Imagine that the user want to part of the order with a memecoin for any reason (so he would pay with ETH + Memecoin). 

For now focus on support of two tokens, but if possible follow good principles and make it easy to support 3 tokens in the future.

**Comment by wheval** [comment]
Okay. Would work on that ASAP

**Review by machuwey — APPROVED** [review]

**Pull request merged**
