### PR TITLE
fix: linted all cairo code

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
@machuwey PTAL

### CODE REVIEW

**Comment by machuwey** [comment]
> @machuwey PTAL

Hi @SoarinSkySagar , could you specify what plugin / dependency to lint the code.

**Comment by SoarinSkySagar** [comment]
> > @machuwey PTAL
> 
> Hi @SoarinSkySagar , could you specify what plugin / dependency to lint the code. 

hi @machuwey, its the command `scarb fmt`

To check if all the code is properly linted, use `scarb fmt --check`

**Comment by SoarinSkySagar** [comment]
@machuwey I linted the newest changes too

**Comment by machuwey** [comment]
> > > @machuwey PTAL
> > 
> > 
> > Hi @SoarinSkySagar , could you specify what plugin / dependency to lint the code.
> 
> hi @machuwey, its the command `scarb fmt`
> 
> To check if all the code is properly linted, use `scarb fmt --check`

Okey nice, please add the to /contracts README.md file to use this command, so next contributors are aware.

**Comment by SoarinSkySagar** [comment]
@machuwey added the command to the contracts/README file and added myself as a contributor

**Review by machuwey — APPROVED** [review]

**Pull request merged**
